# Exported from https://tiplanet.org/pb/ on Mon Dec 11 16:34:41 2023 (CET)

# ----------------------------
# Program Options
# ----------------------------

NAME         ?= BOUNCE
ICON         ?= icon.png
DESCRIPTION  ?= ""
COMPRESSED   ?= YES
ARCHIVED     ?= YES

# ----------------------------
# Compile Options
# ----------------------------

CFLAGS   ?= -Oz -W -Wall -Wextra -Wwrite-strings
CXXFLAGS ?= -Oz -W -Wall -Wextra -Wwrite-strings

# ----------------------------

include $(shell cedev-config --makefile)
